"""Render spikes/results/RESULTS.md from the recorded raw evidence.

Reads every spikes/results/raw/report-run*.json, the Linux validation and the
dependency assessment, and emits a normalised comparison. Deliberately does
not make the decision - it presents evidence; the decision lives in
docs/TECHNOLOGY-DECISIONS.md.
"""
import json
import statistics
from pathlib import Path

SPIKES = Path(__file__).resolve().parents[1]
RAW = SPIKES / "results" / "raw"
OUT = SPIKES / "results" / "RESULTS.md"

# Benchmarks where a lower value is better (all timings). Memory is bytes.
LOWER_BETTER = True


def load_runs():
    runs = []
    for p in sorted(RAW.glob("report-run*.json")):
        runs.append((p.name, json.loads(p.read_text(encoding="utf-8"))))
    return runs


def collect(runs):
    """benchmark -> runtime -> [median per run]

    Only the final run is aggregated. Runs 1 and 2 predate the fairness fixes
    to fsscan/git/concurrency (sequential-await on the Node side, serialised
    subprocesses and process-pool-only on the Python side) and mixing them in
    would misreport those three benchmarks. They are retained as provenance.
    """
    table = {}
    for _, rep in runs[-1:]:
        for _group, entry in rep.get("benchmarks", {}).items():
            if not isinstance(entry, dict):
                continue
            for runtime, payload in entry.items():
                if runtime not in ("node", "python"):
                    continue
                for res in payload.get("results", []):
                    table.setdefault(res["benchmark"], {}).setdefault(runtime, []).append(res["median"])
    return table


def fmt(v, unit):
    if v is None:
        return "n/a"
    if unit == "bytes":
        return f"{v / 1048576:.1f} MB"
    if v >= 1000:
        return f"{v / 1000:.2f} s"
    return f"{v:.1f} ms"


def units_for(runs, benchmark):
    for _, rep in runs:
        for entry in rep.get("benchmarks", {}).values():
            if not isinstance(entry, dict):
                continue
            for payload in entry.values():
                if not isinstance(payload, dict):
                    continue
                for res in payload.get("results", []):
                    if res["benchmark"] == benchmark:
                        return res["unit"]
    return "ms"


def main():
    runs = load_runs()
    if not runs:
        raise SystemExit("no raw runs found")
    table = collect(runs)
    latest = runs[-1][1]
    linux = json.loads((RAW / "linux-validation.json").read_text(encoding="utf-8"))
    deps = json.loads((RAW / "dependency-assessment.json").read_text(encoding="utf-8"))

    L = []
    a = L.append
    a("# EPIC-005 - Measured Evidence")
    a("")
    a("Generated by `spikes/tools/report.py` from the raw runs in `spikes/results/raw/`.")
    a("This file reports **what was measured**. The decision and its reasoning live in")
    a("`docs/TECHNOLOGY-DECISIONS.md`.")
    a("")

    env = latest["environment"]
    a("## Environment")
    a("")
    a(f"- OS: {env['os']} ({env['machine']}, {env['cpu_count']} logical CPUs)")
    a(f"- Node: {env['node']} / npm {env['npm']}")
    a(f"- Python: {env['python']}")
    a(f"- {env['git']}; {env['docker']}")
    a("- PostgreSQL: 17.11 (pgvector/pgvector:pg17) with pgvector 0.8.6, in Docker")
    a(f"- Runs recorded: {', '.join(n for n, _ in runs)}")
    a("")
    a("Corpus (deterministic, seed 20260830, identical bytes for both runtimes):")
    a("2,000 code files (.ts/.py/.js/.md/.json), 5 PDFs x 20 pages, 5 DOCX, 5 XLSX")
    a("(4 sheets x 2,000 rows), 5 CSVs (50k rows), 16 malformed/adversarial cases,")
    a("and one 84 MB / 2,000,001-row CSV.")
    a("")

    a("## Startup and footprint")
    a("")
    s = latest["startup"]
    a("| Measure | Node | Python | Ratio |")
    a("|---|---:|---:|---|")
    nr, pr = s["node_runtime"]["median"], s["python_runtime"]["median"]
    na, pa = s["node_app"]["median"], s["python_app"]["median"]
    a(f"| Bare runtime spawn (median of {s['node_runtime']['n']}) | {nr:.0f} ms | {pr:.0f} ms | "
      f"Python {nr / pr:.2f}x faster |")
    a(f"| App start, core deps loaded (median of {s['node_app']['n']}) | {na:.0f} ms | {pa:.0f} ms | "
      f"Node {pa / na:.2f}x faster |")
    a(f"| Dependency load cost (app - bare) | {na - nr:.0f} ms | {pa - pr:.0f} ms | "
      f"Node {(pa - pr) / (na - nr):.2f}x faster |")
    a("")
    a("> Caveat: this machine has a process-spawn floor of roughly 350-420 ms "
      "(Windows Defender real-time scanning), which dominates the bare-runtime row. "
      "The dependency-load delta and the MCP startup figure below are the meaningful signals.")
    a("")
    f = latest["footprint"]
    pyf = f["python"]
    py_ex_pip = pyf["site_packages_bytes"] - (pyf["pip_bytes"] or 0)
    a("| Footprint | Node | Python |")
    a("|---|---:|---:|")
    a(f"| Install size | {f['node']['bytes'] / 1048576:.0f} MB | "
      f"{pyf['venv_bytes'] / 1048576:.0f} MB venv "
      f"({py_ex_pip / 1048576:.0f} MB excluding pip) |")
    a(f"| Files on disk | {f['node']['files']:,} | {pyf['files']:,} |")
    a(f"| Packages installed | {f['node']['packages']} | {pyf['packages']} |")
    a(f"| Resident memory, core deps loaded | "
      f"{fmt(statistics.median(table['memory']['node']), 'bytes')} | "
      f"{fmt(statistics.median(table['memory']['python']), 'bytes')} |")
    a("")
    a("> The Node figure includes `tree-sitter-wasms` (50 MB) which bundles ~40 grammars "
      "where Ferret needs 3; a targeted grammar set would cut roughly 45 MB. "
      "The Python venv figure includes ~11 MB of pip that a shipped product would not carry.")
    a("")

    a("## Benchmark fairness corrections")
    a("")
    a("Three benchmarks were rewritten after the first two runs exposed that they were")
    a("measuring my implementation choices rather than the runtimes:")
    a("")
    a("- `fsscan`: the Node version used a sequential `await readFile` loop (963 ms). Bounded")
    a("  parallelism cut it to 363 ms. Both runtimes now measure **both** a sequential and a")
    a("  concurrent strategy and are credited with their best.")
    a("- `git`: the Python version ran its three git calls serially while Node ran them via")
    a("  `Promise.all`. With the calls parallelised, Python went 435 ms -> 155 ms, turning a")
    a("  2.4x Node win into a tie.")
    a("- `concurrency`: Python used only a process pool, which is expensive on Windows. Adding")
    a("  a thread pool (hashlib and file I/O release the GIL) took Python from 512 ms to 231 ms,")
    a("  turning a 2x Node win into a Python win.")
    a("")
    a("Two of the three corrections moved the result **against** the eventual recommendation.")
    a("")
    a("## Benchmark results (Windows host)")
    a("")
    a("From the final run (`report-run3-final.json`), the only run made after the fairness")
    a("corrections described above. Ratio is the slower over the faster.")
    a("")
    a("| Benchmark | Node | Python | Faster |")
    a("|---|---:|---:|---|")
    order = ["fsscan", "concurrency", "git", "treesitter", "parse_pdf", "parse_docx",
             "parse_xlsx", "parse_csv", "largefile_csv", "postgres_insert",
             "postgres_index", "postgres_fts_query", "mcp_startup", "mcp_tool_small",
             "mcp_tool_large"]
    for b in order:
        if b not in table:
            continue
        unit = units_for(runs, b)
        n = statistics.median(table[b].get("node", [])) if table[b].get("node") else None
        p = statistics.median(table[b].get("python", [])) if table[b].get("python") else None
        if n is None or p is None:
            a(f"| `{b}` | {fmt(n, unit)} | {fmt(p, unit)} | - |")
            continue
        if n < p:
            verdict = f"**Node** {p / n:.2f}x"
        elif p < n:
            verdict = f"**Python** {n / p:.2f}x"
        else:
            verdict = "tie"
        a(f"| `{b}` | {fmt(n, unit)} | {fmt(p, unit)} | {verdict} |")
    a("")

    a("## Cross-platform (Linux, containers)")
    a("")
    a(f"Node `{linux['method']['node_image']}`, Python `{linux['method']['python_image']}`. "
      "macOS was **not** measured - no macOS host was available.")
    a("")
    a("| Benchmark | Node (Linux) | Python (Linux) | Faster |")
    a("|---|---:|---:|---|")
    for b, v in linux["benchmarks_median_ms"].items():
        n, p = v["node"], v["python"]
        verdict = f"**Node** {p / n:.2f}x" if n < p else f"**Python** {n / p:.2f}x"
        a(f"| `{b}` | {fmt(n, 'ms')} | {fmt(p, 'ms')} | {verdict} |")
    a("")
    for note in linux["findings"]:
        a(f"- {note}")
    a("")

    a("## Robustness on malformed and adversarial input")
    a("")
    a("16 cases per runtime, each parsed in an isolated process with a 30 s timeout: "
      "truncated (50% and 5%), bit-corrupted, empty, wrong-magic, a decompression-amplification "
      "OOXML (40 MB expanding from a tiny archive), and an OOXML carrying an external-entity (XXE) declaration.")
    a("")
    a("| Outcome | Node | Python |")
    a("|---|---:|---:|")
    keys = sorted(set(linux["robustness_tally"]["node"]) | set(linux["robustness_tally"]["python"]))
    for k in keys:
        a(f"| {k} | {linux['robustness_tally']['node'].get(k, 0)} | "
          f"{linux['robustness_tally']['python'].get(k, 0)} |")
    a("")
    a("- **No crashes, no hangs, no timeouts in either stack.** Every parser in both stacks "
      "either rejected hostile input or returned without stalling.")
    a("- **Neither stack resolved the XXE external entity.** Verified directly: the target "
      "file's contents did not appear in the extracted text.")
    a("- **Behavioural difference that matters for Ferret:** on the XXE document `mammoth` (Node) "
      "raised an error, while `python-docx` returned **empty text with no error**. Silent emptiness "
      "would let Ferret record \"this document has no content\" as evidence. Under Governance 6 "
      "(Evidence Before Inference) a loud rejection is the safer failure mode.")
    a("- Both CSV readers accept corrupt CSV without complaint - inherent to CSV, not a defect, "
      "but it means CSV ingestion needs Ferret-side validation rather than parser-side trust.")
    a("")

    a("## Dependency, licence and maintenance assessment")
    a("")
    a("| | Node | Python |")
    a("|---|---:|---:|")
    a(f"| Packages installed | {f['node']['packages']} | {pyf['packages']} |")
    nv = deps["node"]["vulnerabilities"]
    a(f"| Vulnerabilities before remediation | {nv['initial']['high']} high, "
      f"{nv['initial']['moderate']} moderate | 25 advisories across pypdf and mcp |")
    a(f"| Vulnerabilities after remediation | {nv['after_remediation']['high']} high, "
      f"{nv['after_remediation']['moderate']} moderate | 0 (pip-audit clean) |")
    a(f"| Deprecated transitive packages | {len(deps['node']['deprecated_transitives'])} | 0 |")
    a("| Native builds required | 0 | 0 |")
    a("| Copyleft on a mandatory path | no | **yes** - psycopg is LGPL-3.0-only |")
    a("| Undeclared licence in tree | **yes** - `buffers@0.1.1` | no |")
    a("")
    for o in deps["cross_stack_observations"]:
        a(f"- {o}")
    a("")

    a("## Raw evidence")
    a("")
    for n, _ in runs:
        a(f"- `spikes/results/raw/{n}`")
    a("- `spikes/results/raw/linux-validation.json`")
    a("- `spikes/results/raw/dependency-assessment.json`")
    a("")
    a("Reproduce with:")
    a("")
    a("```")
    a("python spikes/tools/gen_corpus.py")
    a("python spikes/tools/gen_malformed.py")
    a("FERRET_PG_URL=postgresql://... python spikes/tools/run_all.py")
    a("python spikes/tools/report.py")
    a("```")
    a("")

    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
