export {
  CAPABILITIES,
  CAPABILITY_OPERATION_VERSIONS,
  CAPABILITY_VERSIONS,
  Capability,
  CapabilitySupport,
  MINIMUM_CAPABILITY_VERSIONS,
  assertSupported,
  declares,
  operationIntroducedAt,
  describeSupport,
  isCapability,
  isSupportedCapabilityVersion,
  validateCapabilityDeclaration,
  type CapabilityDeclaration,
  type CapabilityLimits,
  type CapabilityVerdict,
} from './capabilities.js';
export {
  DEFAULT_PROVIDER_SETTINGS,
  providerConfigurationWarnings,
  providerSettings,
  secretOptionPredicate,
  type OptionsSchemaIssue,
  type OptionsSchemaResult,
  type ProviderConfigurationWarning,
  type ProviderOptionsSchema,
  type ProviderSettings,
} from './configuration.js';
export {
  MINIMUM_PROVIDER_CONTRACT_VERSION,
  PROVIDER_CONTRACT_VERSION,
  PROVIDER_ID_PATTERN,
  isSupportedContractVersion,
  ProviderKind,
  describeProvider,
  isProviderKind,
  type Provider,
  type ProviderContext,
  type ProviderDescriptor,
  type ProviderHostContext,
} from './contract.js';
export {
  ContentUnavailable,
  RepositoryIdentityKind,
  RepositoryOperation,
  SkipReason,
  type BranchPage,
  type DiscoveredBranch,
  type DiscoveredRepository,
  type DiscoveredWorktree,
  type FileContent,
  type FileContentRequest,
  type RepositoryDiscoveryRequest,
  type RepositoryDiscoveryResult,
  type RepositoryRemote,
  type RepositorySource,
  type SkippedPath,
} from './contracts/source-repository.js';
export {
  discoverProviders,
  providerDiscoveryError,
  type ProviderDiscoveryResult,
  type ProviderDiscoverySkip,
  type ProviderModuleExports,
  type ProviderModuleLoader,
} from './discovery.js';
export { ProviderRegistry } from './registry.js';
export * from './sdk/index.js';

export {
  ParserSupport,
  SegmentKind,
  isContentParser,
  isSegmentKind,
  type ContentParser,
  type ContentSegment,
  type ContentSpan,
  OutlineKind,
  ReferenceKind,
  type CodeReference,
  type OutlineNode,
  type ParseOutput,
  type ParseRequest,
  type ParseTarget,
  type ParseWarning,
} from './contracts/parser.js';

export {
  assertUsable,
  type EmbeddingModel,
  type EmbeddingRequest,
  type EmbeddingResult,
  type EmbeddingSource,
} from './contracts/embedding.js';
