import { effectiveAuthority, SourceAuthority, type CanonicalEntity } from '../domain/index.js';

import { recencyKey, standing } from './freshness.js';
import type { WithheldReport } from './access.js';
import type { QueryPlan } from './planner.js';
import type { RankBreakdown, RankSignals, SearchHit } from './query.js';

/**
 * Saying why a query returned these results in this order — EPIC-063.
 *
 * Three Epics built the material and each deferred the explaining. `QueryPlan`
 * records the shape, the reason, and every strategy that ran or was skipped and
 * why; EPIC-056 and EPIC-057 put `relevance`, `contributors`, `subsumed`,
 * `standing` and `why` on each hit; `WithheldReport` counts what permission
 * removed. None of it reached a client, which had an opaque `score` and no way
 * to ask why one hit beat another.
 *
 * **Every sentence comes from a recorded field.** Nothing is inferred, nothing
 * is generated by a model, and no sentence is composed about source content — so
 * an explanation carries no repository text, needs no EPIC-084 containment, and
 * cannot carry an injected instruction. Where a signal is absent it says so; a
 * plausible sentence with nothing behind it is worse than no sentence.
 */

/** One strategy, as a client reads it. */
export interface StrategyNote {
  readonly strategy: string;
  readonly ran: boolean;
  readonly returned: number;
  /** The recorded reason, verbatim. Never paraphrased. */
  readonly skipped: string | undefined;
}

/** Why one hit ranks where it does. */
export interface HitNote {
  readonly rank: number;
  readonly id: string;
  readonly kind: string;
  /** Which branch matched — a name, never the matched text. */
  readonly matchedIn: string;
  /** Absent when nothing recorded one; see {@link HitNote.unexplained}. */
  readonly score: number | undefined;
  /** What the hit's own relevance was built from, when it was. */
  readonly builtFrom: readonly string[];
  /** How many parts of this thing were folded into it, and of what kinds. */
  readonly folded: readonly string[];
  /** The recorded standing sentence, when standing moved this hit. */
  readonly standing: string | undefined;
  /** Set when no breakdown was recorded, rather than reconstructing one. */
  readonly unexplained: string | undefined;
  /**
   * Why this hit ranks below the one before it — the first ordering key on which
   * the two differ. Absent on the first hit.
   */
  readonly below: string | undefined;
}

export interface QueryExplanation {
  readonly question: string;
  /** The shape EPIC-055 read the question as. */
  readonly readAs: string;
  /** EPIC-055's recorded reason for that reading, verbatim. */
  readonly reason: string;
  /** True when the question had one right answer and ranking was not applied. */
  readonly exact: boolean;
  /** True when a strategy was skipped or failed, so the answer may be short. */
  readonly partial: boolean;
  readonly strategies: readonly StrategyNote[];
  readonly hits: readonly HitNote[];
  readonly withheld: { readonly total: number; readonly byReason: readonly string[] };
  /** What this explanation is not able to tell the caller. */
  readonly limits: readonly string[];
}

/**
 * The ordering keys, in the order EPIC-057 §8.3 applies them.
 *
 * "Why is this above that" is answered by walking these and naming the first one
 * on which the pair differs. That is the whole mechanism, and it is why the
 * answer is a fact about the comparator rather than a judgement about the
 * results.
 */
const KEYS: readonly {
  readonly name: string;
  readonly of: (hit: SearchHit & RankSignals) => number | string;
  readonly describe: (a: number | string, b: number | string) => string;
}[] = [
  {
    name: 'standing',
    of: (hit) => standing(hit.entity),
    describe: (a, b) => `standing ${String(b)} against ${String(a)} — what the source says still exists`,
  },
  {
    name: 'relevance',
    of: (hit) => -hit.score,
    describe: (a, b) => `a weaker text match: ${fixed(-Number(b))} against ${fixed(-Number(a))}`,
  },
  {
    name: 'authority',
    of: (hit) => -effectiveAuthority(hit.authority ?? SourceAuthority.UNKNOWN),
    describe: (a, b) => `a less authoritative source: rank ${String(-Number(b))} against ${String(-Number(a))}`,
  },
  {
    name: 'recency',
    of: (hit) => recencyKey(hit.entity),
    describe: (a, b) =>
      `an older observation: ${describeInstant(String(b))} against ${describeInstant(String(a))}`,
  },
];

function fixed(value: number): string {
  return value.toFixed(4);
}

function describeInstant(value: string): string {
  return value === '' ? 'no recorded observation time' : value;
}

/** Why `hit` ranks below `previous` — the first key on which they differ. */
function whyBelow(previous: SearchHit & RankSignals, hit: SearchHit & RankSignals): string {
  for (const key of KEYS) {
    const before = key.of(previous);
    const after = key.of(hit);
    if (before === after) continue;
    // Descending keys are negated by `of`, so a larger value is always worse and
    // one comparison covers both directions.
    return after > before ? key.describe(before, after) : key.describe(after, before);
  }
  // The tail — kind, then source id, then id — is EPIC-056's determinism device
  // and never a judgement. Reporting it as one would be the explanation
  // inventing a reason the comparator did not have.
  return 'nothing ranked above it: the two are separated only by identity, which is the determinism tail';
}

function kindsOf(ids: readonly string[]): readonly string[] {
  // The fold records ids, not kinds; reporting the count is what the data
  // supports. EPIC-063 §8.1 — say what is recorded, not what would read better.
  return ids.length === 0 ? [] : [`${String(ids.length)} folded into this result`];
}

function noteFor(
  hit: SearchHit & RankSignals,
  index: number,
  previous: (SearchHit & RankSignals) | undefined,
  exact: boolean,
): HitNote {
  const breakdown: RankBreakdown | undefined = hit.ranking;
  return {
    rank: index + 1,
    id: hit.entity.id,
    kind: hit.entity.kind,
    matchedIn: hit.source,
    score: breakdown === undefined ? undefined : hit.score,
    builtFrom: breakdown?.contributors ?? [],
    folded: kindsOf(breakdown?.subsumed ?? []),
    standing: breakdown?.why,
    unexplained:
      breakdown !== undefined
        ? undefined
        : exact
          ? 'answered exactly; no ranking was applied'
          : 'no ranking breakdown was recorded for this hit',
    below: previous === undefined ? undefined : whyBelow(previous, hit),
  };
}

/**
 * Composes the explanation. Pure: same inputs, same output, and it reads
 * nothing — the hits and the plan are the whole of what it is allowed to know.
 */
export function explainQuery(
  question: string,
  plan: QueryPlan,
  hits: readonly (SearchHit & RankSignals)[],
  withheld: WithheldReport,
): QueryExplanation {
  const notes = hits.map((hit, index) => noteFor(hit, index, hits[index - 1], plan.exact));

  const limits: string[] = [];
  if (plan.partial) {
    limits.push('a strategy did not run, so results may be missing rather than absent');
  }
  if (withheld.total > 0) {
    limits.push('some results were withheld; only their count is disclosed, never their content');
  }
  if (notes.some((note) => note.unexplained !== undefined)) {
    limits.push('one or more hits carry no ranking breakdown and are reported unexplained');
  }
  // The honest boundary of the feature, stated on every explanation rather than
  // discovered by a caller who assumed otherwise — EPIC-063 §16.
  limits.push('nothing records what a query did not find, so this cannot say why something is missing');

  return Object.freeze({
    question,
    readAs: plan.shape,
    reason: plan.reason,
    exact: plan.exact,
    partial: plan.partial,
    strategies: Object.freeze(
      plan.strategies.map((outcome) =>
        Object.freeze({
          strategy: outcome.strategy,
          ran: outcome.ran,
          returned: outcome.returned,
          skipped: outcome.skipped,
        }),
      ),
    ),
    hits: Object.freeze(notes.map((note) => Object.freeze(note))),
    withheld: Object.freeze({
      total: withheld.total,
      byReason: Object.freeze(
        Object.entries(withheld.byReason)
          .filter(([, count]) => count !== undefined && count > 0)
          .map(([reason, count]) => `${reason}: ${String(count)}`)
          .sort(),
      ),
    }),
    limits: Object.freeze(limits),
  });
}

/**
 * Renders an explanation as text, in the shape `renderAnswer` and `renderPack`
 * established.
 *
 * No content notice, and that is not an omission: an explanation contains no
 * repository text, so there is nothing for a notice to govern. A notice on a
 * document that needs none teaches a reader to ignore notices.
 */
export function renderExplanation(explanation: QueryExplanation): string {
  const lines = [
    `# Why Ferret answered this way`,
    `question: ${JSON.stringify(explanation.question)}`,
    `read as: ${explanation.readAs} — ${explanation.reason}`,
    `${explanation.exact ? 'exact: one right answer, so nothing was ranked' : 'ranked: relevance, then standing, authority and recency'}`,
    `complete: ${explanation.partial ? 'no — see limits' : 'every strategy ran'}`,
    ``,
    `## strategies`,
  ];

  for (const note of explanation.strategies) {
    lines.push(
      note.ran
        ? `- ${note.strategy}: ran, returned ${String(note.returned)}` +
            (note.skipped === undefined ? '' : ` — ${note.skipped}`)
        : `- ${note.strategy}: did not run — ${note.skipped ?? 'no reason was recorded'}`,
    );
  }

  lines.push(``, `## results`);
  if (explanation.hits.length === 0) lines.push(`- nothing matched`);
  for (const note of explanation.hits) {
    lines.push(
      `${String(note.rank)}. ${note.kind} ${note.id} — matched in ${note.matchedIn}` +
        (note.score === undefined ? '' : `, score ${fixed(note.score)}`),
    );
    if (note.unexplained !== undefined) lines.push(`   ${note.unexplained}`);
    if (note.builtFrom.length > 0) lines.push(`   built from: ${note.builtFrom.join(', ')}`);
    for (const folded of note.folded) lines.push(`   ${folded}`);
    if (note.standing !== undefined) lines.push(`   ${note.standing}`);
    if (note.below !== undefined) lines.push(`   below the previous result by ${note.below}`);
  }

  lines.push(``, `## withheld`);
  lines.push(
    explanation.withheld.total === 0
      ? `- nothing was withheld`
      : `- ${String(explanation.withheld.total)} withheld (${explanation.withheld.byReason.join(', ')})`,
  );

  lines.push(``, `## limits`);
  for (const limit of explanation.limits) lines.push(`- ${limit}`);

  return lines.join('\n');
}

/** Kept for the type, so a caller can name what it is explaining. */
export type ExplainableHit = SearchHit & RankSignals & { readonly entity: CanonicalEntity };
