import { detectContent, type ContentEncoding } from '../parsing/detect.js';

import { baseNameOf, extensionOf, normalizeForMatch } from './paths.js';

/**
 * What a file is, beyond what its tree entry said.
 *
 * EPIC-022 and EPIC-023 identify a file from its path, mode, size and object id.
 * EPIC-024 answers only what is needed to pick a parser. Nothing yet says how
 * many lines a file has, whether it uses CRLF, or — the one that matters —
 * whether anybody wrote it.
 *
 * A repository's `dist/`, its lockfiles, its minified bundles and its vendored
 * dependencies are frequently most of its bytes and almost never the answer to
 * a question. Marking them is not filtering: they stay indexed and answerable.
 * It is giving every consumer downstream a fact each one would otherwise guess
 * at, differently.
 */

export const LineEnding = {
  LF: 'lf',
  CRLF: 'crlf',
  CR: 'cr',
  /** More than one style in the same file. */
  MIXED: 'mixed',
  /** A single line with no terminator, or an empty file. */
  NONE: 'none',
} as const;

export type LineEnding = (typeof LineEnding)[keyof typeof LineEnding];

/**
 * What a file is *for*, in one word.
 *
 * Single-valued because a consumer needs one answer, and precedence-ordered
 * because a file is often several of these at once. `generated` and `vendored`
 * are also independent flags on the structure: a minified bundle inside
 * `node_modules` is genuinely both, and a consumer asking "is this generated"
 * must not get `false` because `vendored` won the classification.
 */
export const FileClassification = {
  /** Content a person wrote for the project. */
  SOURCE: 'source',
  TEST: 'test',
  DOCUMENTATION: 'documentation',
  CONFIGURATION: 'configuration',
  /** Tabular or serialized data, not read as prose or code. */
  DATA: 'data',
  /** Produced by a tool. */
  GENERATED: 'generated',
  /** A dependency's source, kept inside the repository. */
  VENDORED: 'vendored',
  BINARY: 'binary',
} as const;

export type FileClassification = (typeof FileClassification)[keyof typeof FileClassification];

export const FILE_CLASSIFICATIONS: readonly FileClassification[] = Object.freeze(
  Object.values(FileClassification),
);

export interface FileStructure {
  readonly path: string;
  readonly extension: string | undefined;
  readonly mediaType: string;
  readonly binary: boolean;
  readonly encoding: ContentEncoding;
  readonly sizeBytes: number;
  readonly empty: boolean;
  /** Lines of text. `undefined` for binary: the question does not apply. */
  readonly lineCount: number | undefined;
  readonly lineEnding: LineEnding;
  /** `undefined` for binary, for the same reason as `lineCount`. */
  readonly endsWithNewline: boolean | undefined;
  /** Longest line in characters. A minified bundle is one very long line. */
  readonly maxLineLength: number | undefined;
  readonly classification: FileClassification;
  /** What decided the classification. Never empty. */
  readonly classificationReason: string;
  readonly generated: boolean;
  readonly vendored: boolean;
}

/**
 * How far into a file a generated marker is looked for.
 *
 * A marker is a convention about the *top* of a file. Scanning further would
 * make any file that quotes the convention — this one, for instance — generated,
 * and would let a repository hide a file from retrieval by burying a marker in
 * it.
 */
export const MARKER_WINDOW_BYTES = 4096;

/**
 * Paths whose content a tool produced.
 *
 * Anchored on directory boundaries so `distribution/` is not `dist/`. Every
 * pattern is a literal test rather than a regular expression with a quantifier
 * that can backtrack, because these run over attacker-controlled paths.
 */
const GENERATED_DIRECTORIES: readonly string[] = Object.freeze([
  'dist',
  'build',
  'out',
  'coverage',
  '__pycache__',
  'target',
  '.next',
  '.nuxt',
  '.output',
  'generated',
  '__generated__',
]);

const GENERATED_FILENAMES: readonly string[] = Object.freeze([
  'package-lock.json',
  'npm-shrinkwrap.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'composer.lock',
  'gemfile.lock',
  'cargo.lock',
  'poetry.lock',
  'pdm.lock',
  'go.sum',
  'packages.lock.json',
]);

/** Suffixes a generator produces. Checked against the lowercased base name. */
const GENERATED_SUFFIXES: readonly string[] = Object.freeze([
  '.min.js',
  '.min.css',
  '.min.mjs',
  '.js.map',
  '.css.map',
  '.d.ts.map',
  '.pb.go',
  '.pb.cc',
  '.pb.h',
  '_pb2.py',
  '_pb2_grpc.py',
  '.g.dart',
  '.freezed.dart',
  '.designer.cs',
  '.generated.ts',
  '.generated.js',
  '.gen.go',
]);

/** In-content markers, matched case-insensitively against the window. */
const GENERATED_MARKERS: readonly string[] = Object.freeze([
  '@generated',
  'code generated by',
  'do not edit',
  'auto-generated',
  'autogenerated',
  'automatically generated',
  'this file was generated',
]);

const VENDORED_DIRECTORIES: readonly string[] = Object.freeze([
  'node_modules',
  'vendor',
  'vendored',
  'third_party',
  'third-party',
  'thirdparty',
  'bower_components',
  'jspm_packages',
  'pods',
  'site-packages',
  '.venv',
  'venv',
  'eggs',
  '.yarn',
]);

const TEST_DIRECTORIES: readonly string[] = Object.freeze([
  'test',
  'tests',
  '__tests__',
  'spec',
  'specs',
  'testdata',
  '__mocks__',
  'e2e',
]);

const DOCUMENTATION_EXTENSIONS: ReadonlySet<string> = new Set([
  'md',
  'markdown',
  'mdx',
  'rst',
  'adoc',
  'txt',
]);

const CONFIGURATION_EXTENSIONS: ReadonlySet<string> = new Set([
  'json',
  'jsonc',
  'yaml',
  'yml',
  'toml',
  'ini',
  'cfg',
  'conf',
  'properties',
  'env',
]);

const CONFIGURATION_FILENAMES: ReadonlySet<string> = new Set([
  'dockerfile',
  'makefile',
  'justfile',
  'procfile',
  '.gitignore',
  '.gitattributes',
  '.editorconfig',
  '.npmrc',
  '.dockerignore',
]);

const DOCUMENTATION_FILENAMES: ReadonlySet<string> = new Set([
  'readme',
  'changelog',
  'license',
  'licence',
  'notice',
  'contributing',
  'authors',
  'codeowners',
]);

const DATA_EXTENSIONS: ReadonlySet<string> = new Set(['csv', 'tsv', 'ndjson', 'jsonl', 'parquet']);

function segmentsOf(path: string): readonly string[] {
  return normalizeForMatch(path).split('/').filter((segment) => segment.length > 0);
}

/** The first matching directory, so the reason can name it. */
function directoryMatch(path: string, names: readonly string[]): string | undefined {
  // The last segment is the file name, not a directory it sits in.
  const directories = segmentsOf(path).slice(0, -1);
  return directories.find((segment) => names.includes(segment));
}

function suffixMatch(name: string, suffixes: readonly string[]): string | undefined {
  return suffixes.find((suffix) => name.endsWith(suffix));
}

/** Whether a name looks like a test file rather than merely living beside one. */
function testFileMatch(name: string): string | undefined {
  if (/\.(test|spec)\.[a-z0-9]+$/.test(name)) return name.includes('.test.') ? '.test.' : '.spec.';
  if (/^test_[a-z0-9_]+\.py$/.test(name)) return 'test_*.py';
  if (/_test\.(go|py|rb)$/.test(name)) return '_test.*';
  return undefined;
}

interface GeneratedVerdict {
  readonly generated: boolean;
  readonly reason: string | undefined;
}

/** Whether a tool produced this file, and what said so. */
function detectGenerated(path: string, text: string | undefined): GeneratedVerdict {
  const name = baseNameOf(path).toLowerCase();

  if (GENERATED_FILENAMES.includes(name)) return { generated: true, reason: `lockfile ${name}` };

  const suffix = suffixMatch(name, GENERATED_SUFFIXES);
  if (suffix !== undefined) return { generated: true, reason: `generated suffix ${suffix}` };

  const directory = directoryMatch(path, GENERATED_DIRECTORIES);
  if (directory !== undefined) return { generated: true, reason: `build directory ${directory}/` };

  if (text !== undefined) {
    // Only the top of the file: a marker is a convention about where a file
    // starts, and scanning further would mark any file that discusses the
    // convention — and let a repository bury one to change how a file ranks.
    const window = text.slice(0, MARKER_WINDOW_BYTES).toLowerCase();
    const marker = GENERATED_MARKERS.find((candidate) => window.includes(candidate));
    if (marker !== undefined) return { generated: true, reason: `marker "${marker}"` };
  }

  return { generated: false, reason: undefined };
}

interface LineStats {
  readonly lineCount: number;
  readonly lineEnding: LineEnding;
  readonly endsWithNewline: boolean;
  readonly maxLineLength: number;
}

/** One pass, counting lines and their terminators together. */
function lineStats(text: string): LineStats {
  if (text.length === 0) {
    return { lineCount: 0, lineEnding: LineEnding.NONE, endsWithNewline: false, maxLineLength: 0 };
  }

  let lf = 0;
  let crlf = 0;
  let cr = 0;
  let lineStart = 0;
  let maxLineLength = 0;

  for (let index = 0; index < text.length; index += 1) {
    const character = text[index];
    if (character !== '\n' && character !== '\r') continue;

    let terminatorLength = 1;
    if (character === '\r') {
      if (text[index + 1] === '\n') {
        crlf += 1;
        terminatorLength = 2;
        index += 1;
      } else {
        cr += 1;
      }
    } else {
      lf += 1;
    }
    maxLineLength = Math.max(maxLineLength, index + 1 - terminatorLength - lineStart);
    lineStart = index + 1;
  }
  maxLineLength = Math.max(maxLineLength, text.length - lineStart);

  const styles = [lf > 0, crlf > 0, cr > 0].filter(Boolean).length;
  const lineEnding =
    styles > 1
      ? LineEnding.MIXED
      : crlf > 0
        ? LineEnding.CRLF
        : lf > 0
          ? LineEnding.LF
          : cr > 0
            ? LineEnding.CR
            : LineEnding.NONE;

  const endsWithNewline = text.endsWith('\n') || text.endsWith('\r');
  const terminators = lf + crlf + cr;
  // A file ending in a newline has as many lines as terminators; one that does
  // not has a final unterminated line.
  const lineCount = endsWithNewline ? terminators : terminators + 1;

  return { lineCount, lineEnding, endsWithNewline, maxLineLength };
}

interface Classified {
  readonly classification: FileClassification;
  readonly reason: string;
}

/**
 * The one-word answer, in precedence order.
 *
 * Binary first because nothing below it can be true of bytes nobody can read.
 * Vendored before generated because "this is a dependency" is the more useful
 * thing to know about a minified file in `node_modules`; both flags are set
 * regardless, so nothing is lost either way.
 */
function classify(
  path: string,
  binary: boolean,
  generated: GeneratedVerdict,
  vendoredDirectory: string | undefined,
  extension: string | undefined,
): Classified {
  if (binary) return { classification: FileClassification.BINARY, reason: 'content is not text' };
  if (vendoredDirectory !== undefined) {
    return {
      classification: FileClassification.VENDORED,
      reason: `dependency directory ${vendoredDirectory}/`,
    };
  }
  if (generated.generated) {
    return { classification: FileClassification.GENERATED, reason: generated.reason ?? 'generated' };
  }

  const name = baseNameOf(path).toLowerCase();
  const testName = testFileMatch(name);
  if (testName !== undefined) {
    return { classification: FileClassification.TEST, reason: `test file name ${testName}` };
  }
  const testDirectory = directoryMatch(path, TEST_DIRECTORIES);
  if (testDirectory !== undefined) {
    return { classification: FileClassification.TEST, reason: `test directory ${testDirectory}/` };
  }

  const stem = extension === undefined ? name : name.slice(0, name.length - extension.length - 1);
  if (DOCUMENTATION_FILENAMES.has(stem) || (extension !== undefined && DOCUMENTATION_EXTENSIONS.has(extension))) {
    return {
      classification: FileClassification.DOCUMENTATION,
      reason: extension === undefined ? `document name ${stem}` : `document extension .${extension}`,
    };
  }
  if (CONFIGURATION_FILENAMES.has(name) || (extension !== undefined && CONFIGURATION_EXTENSIONS.has(extension))) {
    return {
      classification: FileClassification.CONFIGURATION,
      reason:
        extension !== undefined && CONFIGURATION_EXTENSIONS.has(extension)
          ? `configuration extension .${extension}`
          : `configuration file ${name}`,
    };
  }
  if (extension !== undefined && DATA_EXTENSIONS.has(extension)) {
    return { classification: FileClassification.DATA, reason: `data extension .${extension}` };
  }

  return { classification: FileClassification.SOURCE, reason: 'no other classification applies' };
}

/**
 * Describes a file from its path and its bytes.
 *
 * Detection is EPIC-024's, reused rather than repeated: the media type, the
 * binary verdict, the encoding and the decoded text all come from there, so a
 * file cannot be text to one and binary to the other.
 */
export function describeFileStructure(path: string, bytes: Uint8Array): FileStructure {
  const detection = detectContent(path, bytes);
  const extension = extensionOf(path);
  const generated = detectGenerated(path, detection.text);
  const vendoredDirectory = directoryMatch(path, VENDORED_DIRECTORIES);
  const { classification, reason } = classify(
    path,
    detection.binary,
    generated,
    vendoredDirectory,
    extension,
  );

  const stats = detection.text === undefined ? undefined : lineStats(detection.text);

  return {
    path,
    extension,
    mediaType: detection.mediaType,
    binary: detection.binary,
    encoding: detection.encoding,
    sizeBytes: detection.sizeBytes,
    empty: detection.sizeBytes === 0,
    lineCount: stats?.lineCount,
    lineEnding: stats?.lineEnding ?? LineEnding.NONE,
    endsWithNewline: stats?.endsWithNewline,
    maxLineLength: stats?.maxLineLength,
    classification,
    classificationReason: reason,
    generated: generated.generated,
    vendored: vendoredDirectory !== undefined,
  };
}

/** The `file` attributes a structure supplies. Omits what it cannot say. */
export function fileAttributesFrom(structure: FileStructure): Record<string, unknown> {
  return {
    path: structure.path,
    ...(structure.extension === undefined ? {} : { extension: structure.extension }),
    mediaType: structure.mediaType,
    isBinary: structure.binary,
    classification: structure.classification,
    classificationReason: structure.classificationReason,
    isGenerated: structure.generated,
    isVendored: structure.vendored,
  };
}

/** The `file_version` attributes a structure supplies, given the content hash. */
export function fileVersionAttributesFrom(
  structure: FileStructure,
  contentHash: string,
): Record<string, unknown> {
  return {
    contentHash,
    path: structure.path,
    sizeBytes: structure.sizeBytes,
    encoding: structure.encoding,
    lineEnding: structure.lineEnding,
    ...(structure.lineCount === undefined ? {} : { lineCount: structure.lineCount }),
    ...(structure.endsWithNewline === undefined ? {} : { endsWithNewline: structure.endsWithNewline }),
    ...(structure.maxLineLength === undefined ? {} : { maxLineLength: structure.maxLineLength }),
  };
}
