-- EPIC-009 — identity aliases, with history.
--
-- Generated by `npm run migration:generate -- identity_aliases`, reviewed
-- unchanged.
--
-- Separate from `entity_external_id`, and the distinction is real: an actor's
-- identity is contested and evolves, a commit's node id does not. "These two
-- addresses are the same person" is a judgement — it can be wrong, contested by
-- another provider, and it can stop being true when an address is reassigned —
-- so it needs evidence, confidence, temporal validity and collision detection.
-- None of that belongs on a general-purpose mapping.
--
-- The partial unique index is a backstop, not the mechanism. IdentityStore
-- detects a collision and *reports* it, because a judgement call is a bad thing
-- to learn about from a constraint violation. The index exists so a code path
-- that forgets to check still cannot corrupt the mapping.

CREATE TABLE "ferret"."identity_alias" (
	"id" uuid PRIMARY KEY NOT NULL,
	"system" text NOT NULL,
	"external_id" text NOT NULL,
	"actor_id" uuid NOT NULL,
	"actor_class" text NOT NULL,
	"evidence_id" uuid,
	"confidence" double precision,
	"valid_from" timestamp with time zone NOT NULL,
	"valid_to" timestamp with time zone,
	"first_indexed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_indexed_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "ferret"."identity_alias" ADD CONSTRAINT "identity_alias_actor_id_entity_id_fk" FOREIGN KEY ("actor_id") REFERENCES "ferret"."entity"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "ferret"."identity_alias" ADD CONSTRAINT "identity_alias_evidence_id_evidence_id_fk" FOREIGN KEY ("evidence_id") REFERENCES "ferret"."evidence"("id") ON DELETE set null ON UPDATE no action;
CREATE UNIQUE INDEX "identity_alias_current_idx" ON "ferret"."identity_alias" USING btree ("system","external_id") WHERE "ferret"."identity_alias"."valid_to" IS NULL;
CREATE INDEX "identity_alias_lookup_idx" ON "ferret"."identity_alias" USING btree ("system","external_id");
CREATE INDEX "identity_alias_actor_idx" ON "ferret"."identity_alias" USING btree ("actor_id");
CREATE INDEX "identity_alias_class_idx" ON "ferret"."identity_alias" USING btree ("actor_class");