-- EPIC-010 — derived artefacts and what produced them.
--
-- Generated by `npm run migration:generate -- derived_artifacts`, reviewed
-- unchanged.
--
-- AC-5: a derived index must be able to identify the schema, parser or model
-- version that produced it. Governance §21 says why — an index built by
-- `pdf@6.3.289` is not interchangeable with one the current parser would build,
-- and serving results from the old one means serving results nobody could
-- reproduce.
--
-- Deliberately generic: EPIC-031 will add an index, EPIC-054 embeddings,
-- EPIC-060 answer packs. Each is a derived artefact needing the same question
-- answered — "was this built by something we still trust?" — and reinventing the
-- check three times is how one of the three ends up without it.

CREATE TABLE "ferret"."derived_artifact" (
	"id" uuid PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"scope_id" uuid,
	"producer" text NOT NULL,
	"producer_version" text NOT NULL,
	"schema_version" integer NOT NULL,
	"source_content_hash" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"built_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_checked_at" timestamp with time zone DEFAULT now() NOT NULL,
	"state" text NOT NULL
);

CREATE UNIQUE INDEX "derived_artifact_scope_idx" ON "ferret"."derived_artifact" USING btree ("kind","scope_id");
CREATE INDEX "derived_artifact_producer_idx" ON "ferret"."derived_artifact" USING btree ("producer","producer_version");
CREATE INDEX "derived_artifact_state_idx" ON "ferret"."derived_artifact" USING btree ("state");