/**
 * Ferret core — public entry point.
 *
 * This module is the entire supported surface for embedding Ferret. It exports
 * the runtime, its contracts and its error model.
 *
 * It deliberately imports nothing from `src/cli/**` and nothing provider- or
 * vendor-specific. Providers reach the core through `ProviderRegistry`, never
 * the other way round, so adding GitHub, Jira, a parser or a storage backend
 * never changes what a core consumer depends on. `tests/unit/boundaries.test.ts`
 * enforces this by walking the import graph.
 */

export {
  PACKAGE_NAME,
  RUNTIME_CONTRACT_VERSION,
  SUPPORTED_NODE_RANGE,
  VERSION,
  versionInfo,
  type VersionInfo,
} from './version.js';

export {
  ErrorCode,
  FerretError,
  REDACTED,
  isErrorCode,
  isSecretKey,
  redact,
  redactString,
  serializeError,
  toFerretError,
  type FerretErrorOptions,
  type SerializedError,
} from './errors/index.js';

export {
  LOG_LEVELS,
  createLogger,
  createNullLogger,
  isLogLevel,
  type LogFields,
  type LogLevel,
  type Logger,
  type LoggerOptions,
} from './logging/index.js';

export {
  AuditAction,
  CONFIG_FILE_ENV,
  CONFIG_FILE_VERSION,
  CONFIG_HOME_ENV,
  ConfigPrecedence,
  ConfigStore,
  DEFAULT_DATABASE_PORT,
  DEFAULT_EXCLUSIONS,
  ENV_BINDINGS,
  ENV_PREFIX,
  ExclusionScope,
  MutableConfigSource,
  REPOSITORY_ALLOWED_KEYS,
  REPOSITORY_CONFIG_DIRECTORY,
  REQUIRED_DATABASE_FIELDS,
  SECRET_REF_KEY,
  acquireLock,
  auditLogPath,
  configHome,
  databaseConfigSchema,
  defaultConfigSourceList,
  defaultConfigSources,
  credentialsFor,
  describeConfig,
  describeConfigProtection,
  withoutCredentialFields,
  describeSecretRef,
  effectiveExclusions,
  environmentSource,
  evaluateExclusion,
  exclusionRuleSchema,
  explicitSource,
  ferretConfigSchema,
  filterRepositoryFragment,
  findRepositoryConfig,
  getAt,
  isDatabaseConfigured,
  isExcluded,
  isSecretRef,
  mergeExclusions,
  missingDatabaseFields,
  normalizePath,
  parseConfig,
  parseConfigFile,
  parsePath,
  providerConfigSchema,
  readAudit,
  readConfigFile,
  repositorySource,
  resolveConfig,
  resolveSecretRef,
  resolveSecrets,
  sessionSource,
  userConfigPath,
  userFileSource,
  validateCandidate,
  writeConfigFileAtomically,
  type AuditEntry,
  type ChangeResult,
  type ConfigFile,
  type ConfigSource,
  type DatabaseConfig,
  type DescribeConfigOptions,
  type DefaultSources,
  type DefaultSourcesOptions,
  type ExclusionDecision,
  type ExclusionRule,
  type FerretConfig,
  type ProviderConfig,
  type RepositoryPolicy,
  type ResolvedConfig,
  type SecretRef,
} from './config/index.js';

export {
  EMPTY_MAILMAP,
  LinkRule,
  MAX_MAILMAP_LINES,
  RULE_CONFIDENCE,
  applyMailmap,
  classifyIdentity,
  normalizeGitIdentity,
  parseMailmap,
  proposeIdentityLinks,
  type IdentityClassification,
  type IdentityLinkProposal,
  type Mailmap,
  type MailmapEntry,
  type NormalizedIdentity,
  type RawIdentity,
} from './identity/index.js';

export {
  CODE_MODIFIERS,
  CODE_SYMBOL_KIND,
  CODE_SYMBOL_KINDS,
  DEFAULT_SYMBOL_SOURCE_SYSTEM,
  CodeSymbolKind,
  MAX_SIGNATURE_LENGTH,
  buildCodeSymbols,
  codeSymbolAttributes,
  codeSymbolAttributesFrom,
  codeSymbolEntityInput,
  codeSymbolId,
  codeSymbolKindOf,
  codeSymbolTree,
  registerCodeSymbolKind,
  FILE_DECLARES_SYMBOL,
  FILE_REFERENCES_SYMBOL,
  SYMBOL_REFERENCES_SYMBOL,
  ResolutionRule,
  UnresolvedReason,
  resolveReferences,
  type ReferenceResolution,
  type ResolvedReference,
  type UnresolvedReference,
  symbolScope,
  symbolSourceId,
  type CodeSymbol,
  type CodeSymbolContext,
  type CodeSymbolNode,
  type IndexedSymbol,
  type SymbolIndexPort,
  type SymbolIndexReport,
  type SymbolQuery,
} from './code/index.js';

export {
  FILE_CLASSIFICATIONS,
  FileClassification,
  LineEnding,
  MARKER_WINDOW_BYTES,
  baseNameOf,
  describeFileStructure,
  extensionOf,
  fileAttributesFrom,
  fileVersionAttributesFrom,
  normalizeForMatch,
  type FileStructure,
} from './files/index.js';

export {
  DEFAULT_MAX_PARSE_BYTES,
  DETECTION_WINDOW_BYTES,
  MEDIA_TYPES,
  OCTET_STREAM,
  PLAIN_TEXT,
  UNPARSED_REASONS,
  ParserFramework,
  UnparsedReason,
  detectContent,
  mediaTypeForPath,
  parsersFrom,
  type ContentDetection,
  type ContentEncoding,
  type ParseInput,
  type ParseOutcome,
  type ParsedContent,
  type ParserFrameworkOptions,
  type UnparsedContent,
} from './parsing/index.js';

export {
  MINIMUM_NODE_MAJOR,
  detectEnvironment,
  detectGit,
  type EnvironmentReport,
  type GitInfo,
} from './environment/index.js';

export {
  CORE_DEPENDENCY_CHECKS,
  DependencyStatus,
  DiagnosisSeverity,
  HealthArea,
  aggregateStatus,
  buildDoctorReport,
  buildReport,
  componentFrom,
  countBySeverity,
  diagnose,
  gitAvailableCheck,
  isHealthy,
  isUsable,
  nodeVersionCheck,
  plannedCapabilityComponents,
  synchronizationComponent,
  type SyncProgress,
  probeCore,
  severityOf,
  summarize,
  worseOf,
  type BuildReportInput,
  type CoreProbe,
  type DependencyCheck,
  type DependencyCheckContext,
  type DependencyCheckResult,
  type Diagnosis,
  type DoctorReport,
  type HealthComponent,
  type HealthReport,
  type ProbeOptions,
} from './diagnostics/index.js';

export {
  CAPABILITIES,
  CAPABILITY_OPERATION_VERSIONS,
  CAPABILITY_VERSIONS,
  Capability,
  CapabilitySupport,
  DEFAULT_PROVIDER_SETTINGS,
  MINIMUM_CAPABILITY_VERSIONS,
  MINIMUM_PROVIDER_CONTRACT_VERSION,
  PROVIDER_CONTRACT_VERSION,
  PROVIDER_ID_PATTERN,
  assertSupported,
  declares,
  operationIntroducedAt,
  describeSupport,
  isCapability,
  isSupportedCapabilityVersion,
  isSupportedContractVersion,
  validateCapabilityDeclaration,
  ParserSupport,
  ProviderKind,
  ProviderRegistry,
  SegmentKind,
  describeProvider,
  isContentParser,
  isSegmentKind,
  isProviderKind,
  providerConfigurationWarnings,
  providerSettings,
  secretOptionPredicate,
  type CapabilityDeclaration,
  type CapabilityLimits,
  type CapabilityVerdict,
  type ContentParser,
  type ContentSegment,
  type ContentSpan,
  type OptionsSchemaIssue,
  type CodeReference,
  OutlineKind,
  ReferenceKind,
  type OutlineNode,
  type ParseOutput,
  type ParseRequest,
  type ParseTarget,
  type ParseWarning,
  type OptionsSchemaResult,
  type Provider,
  type ProviderConfigurationWarning,
  type ProviderContext,
  type ProviderDescriptor,
  type ProviderHostContext,
  type ProviderOptionsSchema,
  type ProviderSettings,
  // EPIC-012 — the Provider SDK. Test doubles are deliberately absent: they
  // ship under `@indoulia/ferret/testing`.
  BaseProvider,
  BatchEmitter,
  Emitter,
  MAX_CURSOR_LENGTH,
  ProviderState,
  RateLimiter,
  abortableDelay,
  decodeCursor,
  encodeCursor,
  interrupted,
  isAbortError,
  linkSignals,
  nextDelayMs,
  paginate,
  retry,
  throwIfAborted,
  withDeadline,
  type BatchCounts,
  type DerivedSignal,
  type EmissionIdentity,
  type EmittedEntityInput,
  type EmittedEvidenceInput,
  type EmittedRelationshipInput,
  type Page,
  type PageRequest,
  type ProviderOperationContext,
  type RateLimiterOptions,
  type RateLimiterStats,
  type RetryAttemptInfo,
  type RetryOptions,
  // EPIC-017 — the source.repository capability contract. The Git provider that
  // implements it ships separately, at `@indoulia/ferret/git`.
  ContentUnavailable,
  RepositoryIdentityKind,
  RepositoryOperation,
  SkipReason,
  type BranchPage,
  type DiscoveredBranch,
  type DiscoveredRepository,
  type DiscoveredWorktree,
  type FileContent,
  type FileContentRequest,
  type RepositoryDiscoveryRequest,
  type RepositoryDiscoveryResult,
  type RepositoryRemote,
  type RepositorySource,
  type SkippedPath,
} from './providers/index.js';

export {
  ANSWER_FORMAT_VERSION,
  AnswerCompleteness,
  AnswerPackBuilder,
  CONTENT_NOTICE,
  ContextPackBuilder,
  DEFAULT_ANSWER_BUDGET,
  DEFAULT_BUDGET,
  ESTIMATE_MARGIN,
  EVIDENCE_CANDIDATE_WINDOW,
  EvidenceExclusion,
  MAX_BUDGET,
  MAX_EVIDENCE_PER_FIELD,
  MAX_EVIDENCE_PER_ITEM,
  PACK_FORMAT_VERSION,
  TokenBudget,
  TruncationReason,
  estimateJsonTokens,
  estimateTokens,
  MAX_ANSWER_BUDGET,
  MAX_ANSWER_CANDIDATES,
  MAX_ANSWER_CLAIMS,
  MAX_CITATIONS_PER_CLAIM,
  renderAnswer,
  renderPack,
  selectEvidence,
  type AnswerCandidate,
  type AnswerCitation,
  type AnswerClaim,
  type AnswerDependencies,
  type AnswerPack,
  type AnswerRequest,
  type ContextPack,
  type EvidenceReader,
  type EvidenceSelection,
  type ExcludedEvidence,
  type PackItem,
  type PackOmission,
  type PackRequest,
  type SelectedEvidence,
  type SelectionOptions,
} from './context/index.js';

export {
  DEFAULT_LIMIT,
  Direction,
  NOTHING_WITHHELD,
  PUBLIC_ACCESS,
  WithheldTally,
  WithholdReason,
  assertUsableAccess,
  includedRepositories,
  permits,
  restricts,
  visibleEntities,
  withholds,
  type AccessContext,
  type SearchResult,
  type WithheldReport,
  HitSource,
  MAX_LIMIT,
  boundedLimit,
  boundedOffset,
  type EntityQuery,
  type Neighbour,
  type ReferenceCompleteness,
  type RetrievalPort,
  type SearchHit,
  type SearchQuery,
  MAX_TRAVERSAL_DEPTH,
  TraversalBound,
  traverseFrom,
  type HopReader,
  boundedDepth,
  type TraversalPath,
  type TraversalQuery,
  type TraversalResult,
  type TraversalStep,
} from './retrieval/index.js';

export {
  CONTENT_ARTIFACT_KIND,
  contentProducerIdentity,
  CONTENT_PRODUCER,
  ContentStageSkip,
  contentScopeId,
  runContentStage,
  INDEXER_PRODUCER,
  INDEX_ARTIFACT_KIND,
  RepositoryIndexer,
  assertIndexed,
  watermarkScopeId,
  type ContentArtifactStore,
  type ContentBlobWriter,
  type RunJournal,
  type SyncCursors,
  type ContentCounts,
  type ContentReader,
  type DerivedArtifactRecord,
  type EntityWriter,
  type EvidenceWriter,
  type IndexOptions,
  type IndexReport,
  type IndexableSource,
  type IndexerDependencies,
  type LifecycleCounts,
  type LifecycleStore,
  type PendingLifecycleChange,
  type RelationshipWriter,
  type WatermarkStore,
  type WriteCounts,
} from './indexing/index.js';

export {
  DisposableStack,
  FerretRuntime,
  RuntimeState,
  SHUTDOWN_SIGNALS,
  canTransition,
  createRuntime,
  installSignalHandlers,
  isTerminal,
  type Disposable,
  type RuntimeContext,
  type RuntimeOptions,
  type SignalHandlerOptions,
} from './runtime/index.js';

export {
  ENTITY_ATTRIBUTE_SCHEMAS,
  ENTITY_KINDS,
  ENTITY_SCHEMA_VERSION,
  EntityKind,
  LIFECYCLE_STATES,
  LifecycleState,
  UUID_PATTERN,
  assertCanonicalEntity,
  canonicalId,
  canonicalKey,
  contentHash,
  createEntity,
  encodeKeyParts,
  entityInputSchema,
  entityKindDefinition,
  DEFAULT_MEMORY_LIMIT,
  MAX_LINEAGE_DEPTH,
  MAX_STATEMENT_LENGTH,
  AUTHORITY_BY_METHOD,
  MEMORY_KINDS,
  RECOVERY_KIND_ORDER,
  recoverSession,
  resumeSession,
  type RecoverOptions,
  type RecoveredMemory,
  type RecoveryBundle,
  type RecoveryOmission,
  type ResumeResult,
  type SessionRecoveryPort,
  SOURCE_AUTHORITIES,
  SourceAuthority,
  UNASSESSED_AUTHORITY,
  authorityFor,
  effectiveAuthority,
  isUnknownAuthority,
  // EPIC-046. Confidence comes from the rule, never from the method.
  CONFIDENCE_BANDS,
  Confidence,
  completenessOf,
  derivedConfidence,
  isUnassessedConfidence,
  type AuthorityOptions,
  SessionCaptureKind,
  SessionStatus,
  advanceSessionCheckpoint,
  createSessionCheckpoint,
  serializeSessionCheckpoint,
  sessionCheckpointInputSchema,
  sessionCheckpointKey,
  verifySessionCheckpointIntegrity,
  type JsonValue,
  type SessionCheckpoint,
  type SessionCheckpointInput,
  continueSession,
  createSession,
  createSessionCapture,
  endSession,
  sessionInputSchema,
  sessionKey,
  touchSession,
  type Session,
  type SessionInput,
  sessionCaptureInputSchema,
  sessionCaptureKey,
  type SessionCapture,
  type SessionCaptureInput,
  MEMORY_MARKERS,
  MemoryKind,
  MemoryOrigin,
  ORIGIN_CONFIDENCE,
  createEngineeringMemory,
  engineeringMemoryInputSchema,
  engineeringMemoryKey,
  entityKindSchema,
  entitySourceSchema,
  extractMemories,
  supersede,
  type EngineeringMemory,
  type EngineeringMemoryInput,
  type ExtractOptions,
  type MemoryEvidence,
  type MemoryMarker,
  fileAttributes,
  fileVersionAttributes,
  externalIdSchema,
  identify,
  isCanonicalId,
  isEntityKind,
  isLifecycleState,
  isUnchanged,
  lifecycleStateSchema,
  registerEntityKind,
  registeredEntityKinds,
  resetEntityKindRegistry,
  stableStringify,
  type CanonicalEntity,
  type CanonicalKeyInput,
  type EntityAttributes,
  type EntityInput,
  type EntityKindDefinition,
  type EntitySource,
  type ExternalId,
} from './domain/index.js';

export {
  OPEN_INTERVAL,
  RELATIONSHIP_TYPES,
  RELATIONSHIP_TYPE_PATTERN,
  RelationshipType,
  createRelationship,
  isOpen,
  isValidAt,
  registerRelationshipType,
  registeredRelationshipTypes,
  relationshipInputSchema,
  relationshipKey,
  relationshipTypeDefinition,
  resetRelationshipTypeRegistry,
  type CanonicalRelationship,
  type RegisterRelationshipTypeOptions,
  type RelationshipInput,
  type RelationshipTypeDefinition,
} from './domain/index.js';

export {
  Completeness,
  EVIDENCE_METHODS,
  EVIDENCE_STATES,
  IntegrityFindingKind,
  IntegritySubject,
  verifyEntity,
  verifyEvidence,
  verifyRelationship,
  type IntegrityFinding,
  EvidenceMethod,
  EvidenceState,
  createEvidence,
  detectConflicts,
  evidenceInputSchema,
  evidenceKey,
  evidenceLocatorSchema,
  integrityHashOf,
  isDirectObservation,
  preferredEvidence,
  redactStatement,
  type CanonicalEvidence,
  type ConflictGroup,
  type EvidenceInput,
  type StatedEvidence,
  type EvidenceLocator,
} from './domain/index.js';

export {
  ACTOR_CLASSES,
  ActorClass,
  actorClassForKind,
  assertSameActorClass,
  createIdentityAlias,
  entityKindForActor,
  identityAliasInputSchema,
  isActorClass,
  aliasKey,
  type IdentityAlias,
  type IdentityAliasInput,
  type IdentityCollision,
} from './domain/index.js';

export {
  GLOBAL_SCOPE,
  SCOPE_KINDS,
  ScopeDecision,
  ScopeKind,
  constrains,
  evaluateScope,
  isInScope,
  mergeSelectors,
  scopeContextSchema,
  scopeSchema,
  scopeSelectorSchema,
  type Scope,
  type ScopeContext,
  type ScopeEvaluation,
  type ScopeSelector,
} from './domain/index.js';

export {
  Compatibility,
  SURFACE_POLICIES,
  VersionedSurface,
  assertSafeToWrite,
  checkCompatibility,
  databaseSchemaPolicy,
  isArtifactStale,
  summarizeCompatibility,
  type CompatibilityReport,
  type CompatibilityVerdict,
  type SurfacePolicy,
} from './domain/index.js';

export {
  assertUsable,
  type EmbeddingModel,
  type EmbeddingRequest,
  type EmbeddingResult,
  type EmbeddingSource,
} from './providers/contracts/embedding.js';

export {
  QueryPlanner,
  QueryShape,
  RRF_K,
  classify,
  fuse,
  type Classification,
  type ExactStrategy,
  type FusedHit,
  type PlannedQuery,
  type PlannedResults,
  type QueryPlan,
  type RankedList,
  type SemanticStrategy,
  type StrategyOutcome,
  type TextStrategy,
} from './retrieval/index.js';

export {
  CORPUS_SCOPE,
  GOLDEN_DATASET_DIR,
  QueryShape as GoldenQueryShape,
  Relevance,
  computeGoldenChecksum,
  loadGoldenDataset,
  loadParsingDataset,
  resolveIdentity,
  type GoldenDataset,
  type GoldenEvidenceExpectation,
  type GoldenExpected,
  type GoldenHistory,
  type GoldenIdentity,
  type GoldenQuery,
} from './evaluation/index.js';

export {
  DEFAULT_K,
  measureParsingQuality,
  measureRetrievalQuality,
  type ParsingDataset,
  type ParsingQualityReport,
  ndcgAtK,
  precisionAtK,
  recallOf,
  reciprocalRank,
  type Grades,
  type MeasurableRetrieval,
  type QueryMeasurement,
  type RetrievalQualityReport,
} from './evaluation/index.js';

// EPIC-092. Metrics and tracing, without a dependency: the W3C format is
// adopted and the SDK is not.
export {
  Metric,
  MetricUnit,
  MetricsRegistry,
  SPAN_DURATION_UNIT,
  Tracer,
  createMetricsRegistry,
  defaultMetrics,
  isTraceparent,
  traceparentOf,
  type CounterValue,
  type HistogramValue,
  type MetricsSnapshot,
  type SpanRecord,
} from './observability/index.js';

// EPIC-085. A durable audit trail, on disk rather than in a table: an audit
// trail that needs the database is absent when the database is the problem.
export {
  AUDIT_KEEP_FILES,
  AUDIT_ROTATE_BYTES,
  AuditCategory,
  AuditOutcome,
  AuditWriter,
  auditEventsPath,
  readAuditEvents,
  type AuditEvent,
} from './audit/index.js';

// EPIC-072. The join between what a tracker says and what a repository shows.
// Records in, canonical knowledge out — no transport and no store, which is
// what lets EPIC-021's GitHub records and EPIC-071's Jira records share it.
export {
  CLOSING_KEYWORDS,
  MAX_REFERENCE_SCAN_CHARACTERS,
  findClosingReferences,
  modelProject,
  type ClosingReference,
  type ProjectModelInput,
  type ProjectModelResult,
  type SkippedRecord,
} from './project/index.js';

// EPIC-119. The universal source connector boundary: the contract a source of
// any shape implements, and the single ingestion path every one of them reaches.
export {
  SOURCE_CONNECTOR_CONTRACT_VERSION,
  ConnectorOperation,
  isSourceConnector,
  sourceIdentityKey,
  type AcquiredRecord,
  type AcquisitionPage,
  type AcquisitionRequest,
  type NormalizationContext,
  type SkippedSourceRecord,
  type SourceConnector,
  type SourceContribution,
  type SourceIdentity,
  type SourceRecordMetadata,
} from './providers/contracts/source-connector.js';
export {
  DEFAULT_INGEST_PAGE_LIMIT,
  INGEST_PRODUCER,
  NO_WRITES,
  PROJECT_ISSUE_RECORD,
  SourceIngestor,
  addWrites,
  ingestSources,
  projectSourceConnector,
  writeContribution,
  type ContributionGraph,
  type ContributionWriters,
  type ContributionWrites,
  type IngestCounts,
  type IngestDependencies,
  type IngestOptions,
  type IngestOutcome,
  type IngestReport,
  type IngestRequest,
  type ProjectConnectorOptions,
} from './connectors/index.js';

// EPIC-073. Releases, deployments, and the commit-graph walk that answers which
// commits a release contains — the one question no release API answers.
export {
  MAX_RELEASE_COMMITS,
  commitsInRelease,
  modelReleases,
  type AncestryOptions,
  type AncestryWalk,
  type ReleaseModelInput,
  type ReleaseModelResult,
} from './project/index.js';

// EPIC-077. Event-driven sources: a webhook says something changed on a server,
// a filesystem watcher says the same about a disk. Both are hints, and
// EPIC-078's reconciliation stays what is actually correct. Ferret verifies and
// normalizes; terminating an HTTP request is the host's.
export {
  DEFAULT_WATCH_DEBOUNCE_MS,
  DeliveryLedger,
  EventSubject,
  MAX_REMEMBERED_DELIVERIES,
  MAX_WATCHED_ROOTS,
  RepositoryWatcher,
  SIGNATURE_REFUSAL_MESSAGE,
  SignatureRefusal,
  SignatureScheme,
  normalizeGithubEvent,
  normalizeJiraEvent,
  verifySignature,
  type NormalizeResult,
  type SignatureVerdict,
  type SourceEvent,
  type WatchOptions,
} from './events/index.js';

// EPIC-051. Two mechanisms: a global identifier resolves by construction, and
// everything else is a proposal a person adjudicates. `IdentityStore.merge`
// remains the only thing that merges.
export {
  CANONICAL_SOURCE_SYSTEM,
  RULE_CONFIDENCE as RESOLUTION_RULE_CONFIDENCE,
  CrossSourceRule,
  canonicalSourceSystem,
  hasGlobalIdentifier,
  hostOf,
  proposeResolutions,
  repositoryIdentifierFor,
  type ActorRecord,
  type IssueRecord,
  type ResolutionInput,
  type ResolutionProposal,
} from './resolution/index.js';

// EPIC-074. The extension framework's own surface: a manifest a package
// declares, read before its code runs.
export {
  ManifestRefusal,
  providerManifestSchema,
  readProviderManifest,
  refusesImport,
  type DiscoveryOptions,
  type ManifestVerdict,
  type ProviderManifest,
  type ProviderManifestReader,
} from './providers/index.js';
