/**
 * Ferret core — public entry point.
 *
 * This module is the entire supported surface for embedding Ferret. It exports
 * the runtime, its contracts and its error model.
 *
 * It deliberately imports nothing from `src/cli/**` and nothing provider- or
 * vendor-specific. Providers reach the core through `ProviderRegistry`, never
 * the other way round, so adding GitHub, Jira, a parser or a storage backend
 * never changes what a core consumer depends on. `tests/unit/boundaries.test.ts`
 * enforces this by walking the import graph.
 */

export {
  PACKAGE_NAME,
  RUNTIME_CONTRACT_VERSION,
  SUPPORTED_NODE_RANGE,
  VERSION,
  versionInfo,
  type VersionInfo,
} from './version.js';

export {
  ErrorCode,
  FerretError,
  REDACTED,
  isErrorCode,
  isSecretKey,
  redact,
  redactString,
  serializeError,
  toFerretError,
  type FerretErrorOptions,
  type SerializedError,
} from './errors/index.js';

export {
  LOG_LEVELS,
  createLogger,
  createNullLogger,
  isLogLevel,
  type LogFields,
  type LogLevel,
  type Logger,
  type LoggerOptions,
} from './logging/index.js';

export {
  AuditAction,
  CONFIG_FILE_ENV,
  CONFIG_FILE_VERSION,
  CONFIG_HOME_ENV,
  ConfigPrecedence,
  ConfigStore,
  DEFAULT_DATABASE_PORT,
  DEFAULT_EXCLUSIONS,
  ENV_BINDINGS,
  ENV_PREFIX,
  ExclusionScope,
  MutableConfigSource,
  REPOSITORY_ALLOWED_KEYS,
  REPOSITORY_CONFIG_DIRECTORY,
  REQUIRED_DATABASE_FIELDS,
  SECRET_REF_KEY,
  acquireLock,
  auditLogPath,
  configHome,
  databaseConfigSchema,
  defaultConfigSourceList,
  defaultConfigSources,
  describeConfig,
  describeSecretRef,
  effectiveExclusions,
  environmentSource,
  evaluateExclusion,
  exclusionRuleSchema,
  explicitSource,
  ferretConfigSchema,
  filterRepositoryFragment,
  findRepositoryConfig,
  getAt,
  isDatabaseConfigured,
  isExcluded,
  isSecretRef,
  mergeExclusions,
  missingDatabaseFields,
  normalizePath,
  parseConfig,
  parseConfigFile,
  parsePath,
  providerConfigSchema,
  readAudit,
  readConfigFile,
  repositorySource,
  resolveConfig,
  resolveSecretRef,
  resolveSecrets,
  sessionSource,
  userConfigPath,
  userFileSource,
  validateCandidate,
  writeConfigFileAtomically,
  type AuditEntry,
  type ChangeResult,
  type ConfigFile,
  type ConfigSource,
  type DatabaseConfig,
  type DescribeConfigOptions,
  type DefaultSources,
  type DefaultSourcesOptions,
  type ExclusionDecision,
  type ExclusionRule,
  type FerretConfig,
  type ProviderConfig,
  type RepositoryPolicy,
  type ResolvedConfig,
  type SecretRef,
} from './config/index.js';

export {
  EMPTY_MAILMAP,
  LinkRule,
  MAX_MAILMAP_LINES,
  RULE_CONFIDENCE,
  applyMailmap,
  classifyIdentity,
  normalizeGitIdentity,
  parseMailmap,
  proposeIdentityLinks,
  type IdentityClassification,
  type IdentityLinkProposal,
  type Mailmap,
  type MailmapEntry,
  type NormalizedIdentity,
  type RawIdentity,
} from './identity/index.js';

export {
  CODE_MODIFIERS,
  CODE_SYMBOL_KIND,
  CODE_SYMBOL_KINDS,
  DEFAULT_SYMBOL_SOURCE_SYSTEM,
  CodeSymbolKind,
  MAX_SIGNATURE_LENGTH,
  buildCodeSymbols,
  codeSymbolAttributes,
  codeSymbolAttributesFrom,
  codeSymbolEntityInput,
  codeSymbolId,
  codeSymbolKindOf,
  codeSymbolTree,
  registerCodeSymbolKind,
  symbolScope,
  symbolSourceId,
  type CodeSymbol,
  type CodeSymbolContext,
  type CodeSymbolNode,
  type IndexedSymbol,
  type SymbolIndexPort,
  type SymbolIndexReport,
  type SymbolQuery,
} from './code/index.js';

export {
  FILE_CLASSIFICATIONS,
  FileClassification,
  LineEnding,
  MARKER_WINDOW_BYTES,
  baseNameOf,
  describeFileStructure,
  extensionOf,
  fileAttributesFrom,
  fileVersionAttributesFrom,
  normalizeForMatch,
  type FileStructure,
} from './files/index.js';

export {
  DEFAULT_MAX_PARSE_BYTES,
  DETECTION_WINDOW_BYTES,
  MEDIA_TYPES,
  OCTET_STREAM,
  PLAIN_TEXT,
  UNPARSED_REASONS,
  ParserFramework,
  UnparsedReason,
  detectContent,
  mediaTypeForPath,
  parsersFrom,
  type ContentDetection,
  type ContentEncoding,
  type ParseInput,
  type ParseOutcome,
  type ParsedContent,
  type ParserFrameworkOptions,
  type UnparsedContent,
} from './parsing/index.js';

export {
  MINIMUM_NODE_MAJOR,
  detectEnvironment,
  detectGit,
  type EnvironmentReport,
  type GitInfo,
} from './environment/index.js';

export {
  CORE_DEPENDENCY_CHECKS,
  DependencyStatus,
  DiagnosisSeverity,
  HealthArea,
  aggregateStatus,
  buildDoctorReport,
  buildReport,
  componentFrom,
  countBySeverity,
  diagnose,
  gitAvailableCheck,
  isHealthy,
  isUsable,
  nodeVersionCheck,
  plannedCapabilityComponents,
  probeCore,
  severityOf,
  summarize,
  worseOf,
  type BuildReportInput,
  type CoreProbe,
  type DependencyCheck,
  type DependencyCheckContext,
  type DependencyCheckResult,
  type Diagnosis,
  type DoctorReport,
  type HealthComponent,
  type HealthReport,
  type ProbeOptions,
} from './diagnostics/index.js';

export {
  CAPABILITIES,
  CAPABILITY_VERSIONS,
  Capability,
  CapabilitySupport,
  DEFAULT_PROVIDER_SETTINGS,
  MINIMUM_CAPABILITY_VERSIONS,
  MINIMUM_PROVIDER_CONTRACT_VERSION,
  PROVIDER_CONTRACT_VERSION,
  PROVIDER_ID_PATTERN,
  assertSupported,
  declares,
  describeSupport,
  isCapability,
  isSupportedCapabilityVersion,
  isSupportedContractVersion,
  validateCapabilityDeclaration,
  ParserSupport,
  ProviderKind,
  ProviderRegistry,
  SegmentKind,
  describeProvider,
  isContentParser,
  isSegmentKind,
  isProviderKind,
  providerConfigurationWarnings,
  providerSettings,
  secretOptionPredicate,
  type CapabilityDeclaration,
  type CapabilityLimits,
  type CapabilityVerdict,
  type ContentParser,
  type ContentSegment,
  type ContentSpan,
  type OptionsSchemaIssue,
  type OutlineNode,
  type ParseOutput,
  type ParseRequest,
  type ParseTarget,
  type ParseWarning,
  type OptionsSchemaResult,
  type Provider,
  type ProviderConfigurationWarning,
  type ProviderContext,
  type ProviderDescriptor,
  type ProviderHostContext,
  type ProviderOptionsSchema,
  type ProviderSettings,
  // EPIC-012 — the Provider SDK. Test doubles are deliberately absent: they
  // ship under `@indoulia/ferret/testing`.
  BaseProvider,
  BatchEmitter,
  Emitter,
  MAX_CURSOR_LENGTH,
  ProviderState,
  RateLimiter,
  abortableDelay,
  decodeCursor,
  encodeCursor,
  interrupted,
  isAbortError,
  linkSignals,
  nextDelayMs,
  paginate,
  retry,
  throwIfAborted,
  withDeadline,
  type BatchCounts,
  type DerivedSignal,
  type EmissionIdentity,
  type EmittedEntityInput,
  type EmittedEvidenceInput,
  type EmittedRelationshipInput,
  type Page,
  type PageRequest,
  type ProviderOperationContext,
  type RateLimiterOptions,
  type RateLimiterStats,
  type RetryAttemptInfo,
  type RetryOptions,
  // EPIC-017 — the source.repository capability contract. The Git provider that
  // implements it ships separately, at `@indoulia/ferret/git`.
  RepositoryIdentityKind,
  RepositoryOperation,
  SkipReason,
  type BranchPage,
  type DiscoveredBranch,
  type DiscoveredRepository,
  type DiscoveredWorktree,
  type RepositoryDiscoveryRequest,
  type RepositoryDiscoveryResult,
  type RepositoryRemote,
  type RepositorySource,
  type SkippedPath,
} from './providers/index.js';

export {
  CONTENT_NOTICE,
  ContextPackBuilder,
  DEFAULT_BUDGET,
  ESTIMATE_MARGIN,
  MAX_BUDGET,
  PACK_FORMAT_VERSION,
  TokenBudget,
  TruncationReason,
  estimateJsonTokens,
  estimateTokens,
  renderPack,
  type ContextPack,
  type PackItem,
  type PackOmission,
  type PackRequest,
} from './context/index.js';

export {
  DEFAULT_LIMIT,
  Direction,
  HitSource,
  MAX_LIMIT,
  boundedLimit,
  type EntityQuery,
  type Neighbour,
  type RetrievalPort,
  type SearchHit,
  type SearchQuery,
  type TraversalQuery,
} from './retrieval/index.js';

export {
  INDEXER_PRODUCER,
  INDEX_ARTIFACT_KIND,
  RepositoryIndexer,
  assertIndexed,
  watermarkScopeId,
  type EntityWriter,
  type EvidenceWriter,
  type IndexOptions,
  type IndexReport,
  type IndexableSource,
  type IndexerDependencies,
  type LifecycleCounts,
  type LifecycleStore,
  type PendingLifecycleChange,
  type RelationshipWriter,
  type WatermarkStore,
  type WriteCounts,
} from './indexing/index.js';

export {
  DisposableStack,
  FerretRuntime,
  RuntimeState,
  SHUTDOWN_SIGNALS,
  canTransition,
  createRuntime,
  installSignalHandlers,
  isTerminal,
  type Disposable,
  type RuntimeContext,
  type RuntimeOptions,
  type SignalHandlerOptions,
} from './runtime/index.js';

export {
  ENTITY_ATTRIBUTE_SCHEMAS,
  ENTITY_KINDS,
  ENTITY_SCHEMA_VERSION,
  EntityKind,
  LIFECYCLE_STATES,
  LifecycleState,
  UUID_PATTERN,
  assertCanonicalEntity,
  canonicalId,
  canonicalKey,
  contentHash,
  createEntity,
  encodeKeyParts,
  entityInputSchema,
  entityKindDefinition,
  DEFAULT_MEMORY_LIMIT,
  MAX_LINEAGE_DEPTH,
  MAX_STATEMENT_LENGTH,
  AUTHORITY_BY_METHOD,
  MEMORY_KINDS,
  RECOVERY_KIND_ORDER,
  recoverSession,
  resumeSession,
  type RecoverOptions,
  type RecoveredMemory,
  type RecoveryBundle,
  type RecoveryOmission,
  type ResumeResult,
  type SessionRecoveryPort,
  SOURCE_AUTHORITIES,
  SourceAuthority,
  authorityFor,
  isUnknownAuthority,
  type AuthorityOptions,
  SessionCaptureKind,
  SessionStatus,
  advanceSessionCheckpoint,
  createSessionCheckpoint,
  serializeSessionCheckpoint,
  sessionCheckpointInputSchema,
  sessionCheckpointKey,
  verifySessionCheckpointIntegrity,
  type JsonValue,
  type SessionCheckpoint,
  type SessionCheckpointInput,
  continueSession,
  createSession,
  createSessionCapture,
  endSession,
  sessionInputSchema,
  sessionKey,
  touchSession,
  type Session,
  type SessionInput,
  sessionCaptureInputSchema,
  sessionCaptureKey,
  type SessionCapture,
  type SessionCaptureInput,
  MEMORY_MARKERS,
  MemoryKind,
  MemoryOrigin,
  ORIGIN_CONFIDENCE,
  createEngineeringMemory,
  engineeringMemoryInputSchema,
  engineeringMemoryKey,
  entityKindSchema,
  entitySourceSchema,
  extractMemories,
  supersede,
  type EngineeringMemory,
  type EngineeringMemoryInput,
  type ExtractOptions,
  type MemoryEvidence,
  type MemoryMarker,
  fileAttributes,
  fileVersionAttributes,
  externalIdSchema,
  identify,
  isCanonicalId,
  isEntityKind,
  isLifecycleState,
  isUnchanged,
  lifecycleStateSchema,
  registerEntityKind,
  registeredEntityKinds,
  resetEntityKindRegistry,
  stableStringify,
  type CanonicalEntity,
  type CanonicalKeyInput,
  type EntityAttributes,
  type EntityInput,
  type EntityKindDefinition,
  type EntitySource,
  type ExternalId,
} from './domain/index.js';

export {
  OPEN_INTERVAL,
  RELATIONSHIP_TYPES,
  RELATIONSHIP_TYPE_PATTERN,
  RelationshipType,
  createRelationship,
  isOpen,
  isValidAt,
  registerRelationshipType,
  registeredRelationshipTypes,
  relationshipInputSchema,
  relationshipKey,
  relationshipTypeDefinition,
  resetRelationshipTypeRegistry,
  type CanonicalRelationship,
  type RegisterRelationshipTypeOptions,
  type RelationshipInput,
  type RelationshipTypeDefinition,
} from './domain/index.js';

export {
  Completeness,
  EVIDENCE_METHODS,
  EVIDENCE_STATES,
  EvidenceMethod,
  EvidenceState,
  createEvidence,
  detectConflicts,
  evidenceInputSchema,
  evidenceKey,
  evidenceLocatorSchema,
  integrityHashOf,
  isDirectObservation,
  preferredEvidence,
  redactStatement,
  type CanonicalEvidence,
  type ConflictGroup,
  type EvidenceInput,
  type EvidenceLocator,
} from './domain/index.js';

export {
  ACTOR_CLASSES,
  ActorClass,
  actorClassForKind,
  assertSameActorClass,
  createIdentityAlias,
  entityKindForActor,
  identityAliasInputSchema,
  isActorClass,
  aliasKey,
  type IdentityAlias,
  type IdentityAliasInput,
  type IdentityCollision,
} from './domain/index.js';

export {
  GLOBAL_SCOPE,
  SCOPE_KINDS,
  ScopeDecision,
  ScopeKind,
  constrains,
  evaluateScope,
  isInScope,
  mergeSelectors,
  scopeContextSchema,
  scopeSchema,
  scopeSelectorSchema,
  type Scope,
  type ScopeContext,
  type ScopeEvaluation,
  type ScopeSelector,
} from './domain/index.js';

export {
  Compatibility,
  SURFACE_POLICIES,
  VersionedSurface,
  assertSafeToWrite,
  checkCompatibility,
  databaseSchemaPolicy,
  isArtifactStale,
  summarizeCompatibility,
  type CompatibilityReport,
  type CompatibilityVerdict,
  type SurfacePolicy,
} from './domain/index.js';

export {
  assertUsable,
  type EmbeddingModel,
  type EmbeddingRequest,
  type EmbeddingResult,
  type EmbeddingSource,
} from './providers/contracts/embedding.js';

export {
  QueryPlanner,
  QueryShape,
  RRF_K,
  classify,
  fuse,
  type Classification,
  type ExactStrategy,
  type FusedHit,
  type PlannedQuery,
  type PlannedResults,
  type QueryPlan,
  type RankedList,
  type SemanticStrategy,
  type StrategyOutcome,
  type TextStrategy,
} from './retrieval/index.js';
