/**
 * Ferret core — public entry point.
 *
 * This module is the entire supported surface for embedding Ferret. It exports
 * the runtime, its contracts and its error model.
 *
 * It deliberately imports nothing from `src/cli/**` and nothing provider- or
 * vendor-specific. Providers reach the core through `ProviderRegistry`, never
 * the other way round, so adding GitHub, Jira, a parser or a storage backend
 * never changes what a core consumer depends on. `tests/unit/boundaries.test.ts`
 * enforces this by walking the import graph.
 */

export {
  PACKAGE_NAME,
  RUNTIME_CONTRACT_VERSION,
  SUPPORTED_NODE_RANGE,
  VERSION,
  versionInfo,
  type VersionInfo,
} from './version.js';

export {
  ErrorCode,
  FerretError,
  REDACTED,
  isErrorCode,
  isSecretKey,
  redact,
  redactString,
  serializeError,
  toFerretError,
  type FerretErrorOptions,
  type SerializedError,
} from './errors/index.js';

export {
  LOG_LEVELS,
  createLogger,
  createNullLogger,
  isLogLevel,
  type LogFields,
  type LogLevel,
  type Logger,
  type LoggerOptions,
} from './logging/index.js';

export {
  AuditAction,
  CONFIG_FILE_ENV,
  CONFIG_FILE_VERSION,
  CONFIG_HOME_ENV,
  ConfigPrecedence,
  ConfigStore,
  DEFAULT_DATABASE_PORT,
  DEFAULT_EXCLUSIONS,
  ENV_BINDINGS,
  ENV_PREFIX,
  ExclusionScope,
  MutableConfigSource,
  REPOSITORY_ALLOWED_KEYS,
  REPOSITORY_CONFIG_DIRECTORY,
  REQUIRED_DATABASE_FIELDS,
  SECRET_REF_KEY,
  acquireLock,
  auditLogPath,
  configHome,
  databaseConfigSchema,
  defaultConfigSourceList,
  defaultConfigSources,
  describeConfig,
  describeSecretRef,
  effectiveExclusions,
  environmentSource,
  evaluateExclusion,
  exclusionRuleSchema,
  explicitSource,
  ferretConfigSchema,
  filterRepositoryFragment,
  findRepositoryConfig,
  getAt,
  isDatabaseConfigured,
  isExcluded,
  isSecretRef,
  mergeExclusions,
  missingDatabaseFields,
  normalizePath,
  parseConfig,
  parseConfigFile,
  parsePath,
  providerConfigSchema,
  readAudit,
  readConfigFile,
  repositorySource,
  resolveConfig,
  resolveSecretRef,
  resolveSecrets,
  sessionSource,
  userConfigPath,
  userFileSource,
  validateCandidate,
  writeConfigFileAtomically,
  type AuditEntry,
  type ChangeResult,
  type ConfigFile,
  type ConfigSource,
  type DatabaseConfig,
  type DefaultSources,
  type DefaultSourcesOptions,
  type ExclusionDecision,
  type ExclusionRule,
  type FerretConfig,
  type ProviderConfig,
  type RepositoryPolicy,
  type ResolvedConfig,
  type SecretRef,
} from './config/index.js';

export {
  MINIMUM_NODE_MAJOR,
  detectEnvironment,
  detectGit,
  type EnvironmentReport,
  type GitInfo,
} from './environment/index.js';

export {
  CORE_DEPENDENCY_CHECKS,
  DependencyStatus,
  DiagnosisSeverity,
  HealthArea,
  aggregateStatus,
  buildDoctorReport,
  buildReport,
  componentFrom,
  countBySeverity,
  diagnose,
  gitAvailableCheck,
  isHealthy,
  isUsable,
  nodeVersionCheck,
  plannedCapabilityComponents,
  probeCore,
  severityOf,
  summarize,
  worseOf,
  type BuildReportInput,
  type CoreProbe,
  type DependencyCheck,
  type DependencyCheckContext,
  type DependencyCheckResult,
  type Diagnosis,
  type DoctorReport,
  type HealthComponent,
  type HealthReport,
  type ProbeOptions,
} from './diagnostics/index.js';

export {
  PROVIDER_CONTRACT_VERSION,
  PROVIDER_ID_PATTERN,
  ProviderKind,
  ProviderRegistry,
  describeProvider,
  isProviderKind,
  type Provider,
  type ProviderContext,
  type ProviderDescriptor,
} from './providers/index.js';

export {
  DisposableStack,
  FerretRuntime,
  RuntimeState,
  SHUTDOWN_SIGNALS,
  canTransition,
  createRuntime,
  installSignalHandlers,
  isTerminal,
  type Disposable,
  type RuntimeContext,
  type RuntimeOptions,
  type SignalHandlerOptions,
} from './runtime/index.js';

export {
  ENTITY_ATTRIBUTE_SCHEMAS,
  ENTITY_KINDS,
  ENTITY_SCHEMA_VERSION,
  EntityKind,
  LIFECYCLE_STATES,
  LifecycleState,
  UUID_PATTERN,
  assertCanonicalEntity,
  canonicalId,
  canonicalKey,
  contentHash,
  createEntity,
  encodeKeyParts,
  entityInputSchema,
  entityKindDefinition,
  entityKindSchema,
  entitySourceSchema,
  externalIdSchema,
  identify,
  isCanonicalId,
  isEntityKind,
  isLifecycleState,
  isUnchanged,
  lifecycleStateSchema,
  registerEntityKind,
  registeredEntityKinds,
  resetEntityKindRegistry,
  stableStringify,
  type CanonicalEntity,
  type CanonicalKeyInput,
  type EntityAttributes,
  type EntityInput,
  type EntityKindDefinition,
  type EntitySource,
  type ExternalId,
} from './domain/index.js';
