import { describe, expect, it } from 'vitest';

import {
  FILE_CLASSIFICATIONS,
  FileClassification,
  LineEnding,
  MARKER_WINDOW_BYTES,
  describeFileStructure,
  extensionOf,
  createEntity,
  fileAttributes,
  fileAttributesFrom,
  fileVersionAttributes,
  fileVersionAttributesFrom,
  type FileStructure,
} from '../../src/index.js';
import { extensionOf as gitExtensionOf } from '../../src/git/index.js';

const encoder = new TextEncoder();

function describeText(path: string, text: string): FileStructure {
  return describeFileStructure(path, encoder.encode(text));
}

describe('line structure', () => {
  it('counts lines and reports LF — AC-1', () => {
    const structure = describeText('src/a.ts', 'one\ntwo\nthree\n');

    expect(structure.lineCount).toBe(3);
    expect(structure.lineEnding).toBe(LineEnding.LF);
    expect(structure.endsWithNewline).toBe(true);
    expect(structure.maxLineLength).toBe(5);
  });

  it('counts an unterminated final line — AC-1', () => {
    const structure = describeText('src/a.ts', 'one\ntwo');

    expect(structure.lineCount).toBe(2);
    expect(structure.endsWithNewline).toBe(false);
  });

  it('reports CRLF', () => {
    const structure = describeText('src/a.ts', 'one\r\ntwo\r\n');
    expect(structure.lineEnding).toBe(LineEnding.CRLF);
    expect(structure.lineCount).toBe(2);
    // The terminator is not part of the line.
    expect(structure.maxLineLength).toBe(3);
  });

  it('reports mixed rather than picking a side — AC-2', () => {
    const structure = describeText('src/a.ts', 'one\r\ntwo\nthree\n');
    expect(structure.lineEnding).toBe(LineEnding.MIXED);
    expect(structure.lineCount).toBe(3);
  });

  it('reports a lone CR', () => {
    expect(describeText('src/a.ts', 'one\rtwo\r').lineEnding).toBe(LineEnding.CR);
  });

  it('reports a single line with no terminator', () => {
    const structure = describeText('src/a.ts', 'just one line');
    expect(structure.lineCount).toBe(1);
    expect(structure.lineEnding).toBe(LineEnding.NONE);
  });

  it('notices a minified bundle by its one enormous line', () => {
    const structure = describeText('src/app.js', `${'x'.repeat(4000)}\n`);
    expect(structure.lineCount).toBe(1);
    expect(structure.maxLineLength).toBe(4000);
  });
});

describe('binary and empty files', () => {
  it('classifies binary and reports no line structure — AC-7', () => {
    const png = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 1, 2]);
    const structure = describeFileStructure('docs/shot.png', png);

    expect(structure.binary).toBe(true);
    expect(structure.classification).toBe(FileClassification.BINARY);
    expect(structure.lineCount).toBeUndefined();
    expect(structure.endsWithNewline).toBeUndefined();
    expect(structure.maxLineLength).toBeUndefined();
  });

  it('reports an empty file as empty, not as binary — AC-8', () => {
    const structure = describeFileStructure('src/a.ts', new Uint8Array(0));

    expect(structure.empty).toBe(true);
    expect(structure.binary).toBe(false);
    expect(structure.classification).toBe(FileClassification.SOURCE);
    expect(structure.lineCount).toBe(0);
  });
});

describe('generated files', () => {
  it.each([
    ['dist/bundle.js', 'build directory dist/'],
    ['packages/web/build/main.js', 'build directory build/'],
    ['package-lock.json', 'lockfile package-lock.json'],
    ['api/service.pb.go', 'generated suffix .pb.go'],
    ['web/app.min.js', 'generated suffix .min.js'],
    ['proto/thing_pb2.py', 'generated suffix _pb2.py'],
  ])('detects %s from its path — AC-3', (path, reason) => {
    const structure = describeText(path, 'anything at all\n');

    expect(structure.generated).toBe(true);
    expect(structure.classificationReason).toBe(reason);
  });

  it('detects a marker in the content — AC-3', () => {
    const structure = describeText('src/schema.ts', '// @generated by a tool\nexport const x = 1;\n');

    expect(structure.generated).toBe(true);
    expect(structure.classification).toBe(FileClassification.GENERATED);
    expect(structure.classificationReason).toContain('@generated');
  });

  it.each(['Code generated by protoc. DO NOT EDIT.', '# Automatically generated', '/* auto-generated */'])(
    'accepts the marker %o',
    (marker) => {
      expect(describeText('src/a.ts', `${marker}\nconst x = 1;\n`).generated).toBe(true);
    },
  );

  it('ignores a marker buried past the window — AC-11', () => {
    // Otherwise a repository could hide a file from retrieval by putting a
    // marker in a comment two thousand lines down.
    const buried = `${'// padding\n'.repeat(MARKER_WINDOW_BYTES / 5)}// @generated\n`;
    const structure = describeText('src/real.ts', buried);

    expect(buried.length).toBeGreaterThan(MARKER_WINDOW_BYTES);
    expect(structure.generated).toBe(false);
  });

  it('does not mark a file that merely discusses generation', () => {
    const structure = describeText(
      'src/detect.ts',
      'export function isGenerated(text: string): boolean {\n  return text.includes(MARKER);\n}\n',
    );
    expect(structure.generated).toBe(false);
    expect(structure.classification).toBe(FileClassification.SOURCE);
  });

  it('does not mistake distribution/ for dist/', () => {
    expect(describeText('distribution/notes.ts', 'const x = 1;\n').generated).toBe(false);
  });
});

describe('vendored files', () => {
  it('detects a dependency directory — AC-4', () => {
    const structure = describeText('node_modules/left-pad/index.js', 'module.exports = 1;\n');

    expect(structure.vendored).toBe(true);
    expect(structure.classification).toBe(FileClassification.VENDORED);
    expect(structure.classificationReason).toContain('node_modules');
  });

  it('reports both flags when a file is vendored and generated — AC-4', () => {
    const structure = describeText('node_modules/thing/dist/thing.min.js', 'var a=1;\n');

    expect(structure.vendored).toBe(true);
    expect(structure.generated).toBe(true);
    // One classification, and it is the more useful of the two.
    expect(structure.classification).toBe(FileClassification.VENDORED);
  });
});

describe('everything else', () => {
  it.each([
    ['src/thing.test.ts', FileClassification.TEST],
    ['src/thing.spec.js', FileClassification.TEST],
    ['app/tests/helper.py', FileClassification.TEST],
    ['pkg/service_test.go', FileClassification.TEST],
    ['app/test_service.py', FileClassification.TEST],
    ['docs/guide.md', FileClassification.DOCUMENTATION],
    ['README', FileClassification.DOCUMENTATION],
    ['CHANGELOG.md', FileClassification.DOCUMENTATION],
    ['tsconfig.json', FileClassification.CONFIGURATION],
    ['deploy/values.yaml', FileClassification.CONFIGURATION],
    ['Dockerfile', FileClassification.CONFIGURATION],
    ['data/rows.csv', FileClassification.DATA],
    ['src/service.ts', FileClassification.SOURCE],
  ])('classifies %s as %s — AC-5', (path, expected) => {
    expect(describeText(path, 'content\n').classification).toBe(expected);
  });

  it('always says what decided the classification — AC-6', () => {
    for (const path of ['src/a.ts', 'dist/a.js', 'docs/a.md', 'a.test.ts', 'node_modules/a/b.js']) {
      const structure = describeText(path, 'x\n');
      expect(structure.classificationReason.length).toBeGreaterThan(0);
    }
  });
});

describe('canonical attributes', () => {
  it('validates against the extended file schema — AC-9', () => {
    const structure = describeText('src/service.ts', 'export const x = 1;\n');
    const parsed = fileAttributes.parse(fileAttributesFrom(structure));

    expect(parsed).toMatchObject({
      path: 'src/service.ts',
      extension: 'ts',
      mediaType: 'text/x-typescript',
      isBinary: false,
      classification: 'source',
      isGenerated: false,
      isVendored: false,
    });
    expect(parsed.classificationReason).toBeTypeOf('string');
  });

  it('validates against the extended file_version schema — AC-9', () => {
    const structure = describeText('src/service.ts', 'export const x = 1;\n');
    const parsed = fileVersionAttributes.parse(
      fileVersionAttributesFrom(structure, 'git-blob:abc123'),
    );

    expect(parsed).toMatchObject({
      contentHash: 'git-blob:abc123',
      sizeBytes: 20,
      lineCount: 1,
      lineEnding: 'lf',
      endsWithNewline: true,
    });
  });

  it('omits line structure for a binary version, rather than claiming zero — AC-7', () => {
    const png = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 1]);
    const attributes = fileVersionAttributesFrom(describeFileStructure('a.png', png), 'git-blob:x');

    expect(attributes).not.toHaveProperty('lineCount');
    expect(attributes).not.toHaveProperty('endsWithNewline');
    expect(() => fileVersionAttributes.parse(attributes)).not.toThrow();
  });

  it('survives a round trip through the canonical entity — AC-9', () => {
    const structure = describeText('dist/app.min.js', 'var a=1;\n');
    const entity = createEntity({
      kind: 'file',
      source: { system: 'git', id: 'dist/app.min.js' },
      attributes: fileAttributesFrom(structure),
    });

    expect(entity.attributes).toMatchObject({ isGenerated: true, classification: 'generated' });
  });

  it('keeps the canonical vocabulary and the derived one identical', () => {
    // `attributes.ts` spells these out rather than importing them, so the
    // canonical model depends on nothing but zod. This is the guard on that.
    const schema = fileAttributes.parse({ path: 'a', classification: 'source' });
    expect(schema.classification).toBe('source');
    for (const classification of FILE_CLASSIFICATIONS) {
      expect(() => fileAttributes.parse({ path: 'a', classification })).not.toThrow();
    }
    expect(() => fileAttributes.parse({ path: 'a', classification: 'invented' })).toThrow();
  });
});

describe('one definition of an extension — AC-12', () => {
  it('is the core one, re-exported by the Git provider', () => {
    expect(gitExtensionOf).toBe(extensionOf);
  });

  it.each([
    ['a/b/c.TS', 'ts'],
    ['.gitignore', undefined],
    ['Makefile', undefined],
    ['archive.tar.gz', 'gz'],
    ['trailing.', undefined],
  ])('reads %s as %s', (path, expected) => {
    expect(extensionOf(path)).toBe(expected);
  });
});
